#!/bin/bash

project_home="$HOME/workspace"
project_session_separator='/'
pss="$project_session_separator"

project() {
    local project_name="$1"

    cd "$project_home"
    if ! test -d "$project_name"; then
        mkdir -p "$project_name"
    fi

    cd "$project_name"

    _initialize_git

    _initialize_environment

    _attach_session
}

_supports_git() {
    hash git >/dev/null 2>&1
}

_initialize_git() {
    if _supports_git; then
        if ! git status >/dev/null 2>&1; then
            git init .
        fi
    fi

    if ! test -r '.gitignore' ;then
        touch '.gitignore'
        git add '.gitignore'
    fi
}

_ignore_file() {
    local file="$1"
    if _supports_git; then
        if ! grep "^$file\$" .gitignore >/dev/null 2>&1; then
            echo "$file" >> .gitignore
            git add .gitignore
        fi
    fi
}

_supports_sessions() {
    hash tmux >/dev/null 2>&1
}

_session_from_project() {
    echo "project-${1//\./_}"
}

_attach_session() {
    local project_name="${1:-${PWD##*/}}"
    local session_name="$(_session_from_project $project_name)"
    if _supports_sessions; then
        exec tmux new-session -t "$session_name"
    fi
}

_supports_direnv() {
    hash direnv >/dev/null 2>&1
}

_initialize_environment() {
    if _supports_direnv && [ ! -f '.envrc' ]; then
        touch '.envrc' && direnv allow '.'
        _ignore_file '.envrc'
    fi
    export HISTFILE="$PWD/.${SHELL##*/}_history"
    _ignore_file ".${SHELL##*/}_history"
}

project "$*"
