#!/bin/sh

project_home="$HOME/Projects"
project_session_separator='/'
pss="$project_session_separator"

project() {
    local project_name="$1"

    cd "$project_home"
    if ! test -d "$project_name"; then
        mkdir -p "$project_name"
    fi

    cd "$project_name"

    _project_initialize_git

    _project_initialize_direnv

    _project_attach_session
}

_project_supports_git() {
    hash git >/dev/null 2>&1
}

_project_initialize_git() {
    if _project_supports_git; then
        if ! git status >/dev/null 2>&1; then
            git init .
        fi
    fi

    if ! test -r '.gitignore' ;then
        touch '.gitignore'
        git add '.gitignore'
    fi
}

_project_ignore_file() {
    local file="$1"
    if _project_supports_git; then
        if ! grep "^$file\$" .gitignore >/dev/null 2>&1; then
            echo "$file" >> .gitignore
            git add .gitignore
        fi
    fi
}

_project_supports_sessions() {
    hash tmux >/dev/null 2>&1
}

_project_list_session_attachments() {
    local project_name="${1:-${PWD##*/}}"
    local session_id=0
    if _project_supports_sessions; then
        tmux list-sessions \
            -F "#{session_name} #{?session_attached,attached,detached}" \
            | grep "^$project_name$pss" | sort | sed "s|^$project_name$pss||"
    fi
}

_project_attach_session() {
    local project_name="${1:-${PWD##*/}}"
    local session_id=0
    if _project_supports_sessions; then
        local first_detached_session="$(
            _project_list_session_attachments | grep 'detached' \
                | head -1 | awk '{ print $1; }'
        )"
        local last_attached_session="$(
            _project_list_session_attachments | grep 'attached' \
                | tail -1 | awk '{ print $1; }'
        )"
        if [ -n "$first_detached_session" ]; then
            echo "Reattaching to detached session $first_detached_session"
            session_id="$first_detached_session"
        elif  [ -n "$last_attached_session" ]; then
            echo "Attaching to next session after $last_attached_session"
            session_id=$(( $last_attached_session + 1 ))
        fi
        exec tmux new-session -A -s "$project_name$pss$session_id"
    fi
}

_project_supports_direnv() {
    hash direnv >/dev/null 2>&1
}

_project_initialize_direnv() {
    if _project_supports_direnv && [ ! -f '.envrc' ]; then
        touch '.envrc' && direnv allow '.'
        _project_ignore_file '.envrc'
    fi
}

project "$*"
